export const authConstants = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    GETTOKEN_REQUEST: "GETTOKEN_REQUEST",
    GETTOKEN_SUCCESS: "GETTOKEN_SUCCESS",
    GETTOKEN_FAILURE: "GETTOKEN_FAILURE",
    GETUSER_REQUEST: "GETUSER_REQUEST",
    GETUSER_SUCCESS: "GETUSER_SUCCESS",
    GETUSER_FAILURE: "GETUSER_FAILURE",
    GET_USERS_SUCCESS:"GET_USERS_SUCCESS"
    
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_CHANGE_STATE_SUCCESS: 'USER_CHANGE_STATE_SUCCESS',
    USER_GETINDEX_REQUEST: 'USER_GETINDEX_REQUEST',
    USER_GETINDEX_SUCCESS: 'USER_GETINDEX_SUCCESS',
    USER_GETINDEX_FAILURE: 'USER_GETINDEX_FAILURE',
    USER_DELETEINDEX_REQUEST: 'USER_DELETEINDEX_REQUEST',
    USER_DELETEINDEX_SUCCESS: 'USER_DELETEINDEX_SUCCESS',
    USER_DELETEINDEX_FAILURE: 'USER_DELETEINDEX_FAILURE',
    RESETINDEX: 'RESETINDEX',
}
export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
    ADD_NEW_CATEGORIES_SUCCESS: 'ADD_NEW_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORIES_FAILURE: 'ADD_NEW_CATEGORIES_FAILURE',
    UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',
    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE'

}
export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
}
export const productConstants = {
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
    GET_PRODUCT_DETAILS_BY_ID_REQUEST:"GET_PRODUCT_DETAILS_BY_ID_REQUEST",
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS:"GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
    GET_PRODUCT_DETAILS_BY_ID_FAILURE:"GET_PRODUCT_DETAILS_BY_ID_FAILURE"
}
export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE'
}
export const indexConstants = {
    GET_INDEX_DETAILS_REQUEST: "GET_INDEX_DETAILS_REQUEST",
    GET_INDEX_DETAILS_SUCCESS: "GET_INDEX_DETAILS_SUCCESS",
    GET_INDEX_DETAILS_FAILURE: "GET_INDEX_DETAILS_FAILURE",
    NEXTPAGE_REQUEST: 'NEXTPAGE_REQUEST',
    NEXTPAGE_SUCCESS: 'NEXTPAGE_SUCCESS',
    NEXTPAGE_FAILURE: 'NEXTPAGE_FAILURE'
};